
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matthew Laikhram
 */
public class CompScenarioSim extends javax.swing.JFrame {

    /**
     * Creates new form ProjectMM
     */
    public CompScenarioSim(File f) throws FileNotFoundException {
        Scanner scanner = new Scanner(f);
        scanner.useDelimiter("\r\n");
        
        ArrayList<LinkedPanelNode> nodes = new ArrayList<LinkedPanelNode>();
        
        String description;
        String movie;
        String passcode;
        
        while (scanner.hasNext()) {
            description = scanner.next();
            movie = scanner.next();
            passcode = scanner.next();
            nodes.add(new LinkedPanelNode(description, movie, passcode));
        }
        for(int i = 1; i < nodes.size(); ++i) {
            nodes.get(i-1).setNext(nodes.get(i));
        }
        link = new LinkedPanel(nodes.get(0));
        initComponents();
        add(link);
    }
    
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(link.getPreferredSize()
        );
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompScenarioSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompScenarioSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompScenarioSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompScenarioSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new CompScenarioSim(new File(System.getProperty("user.dir") + "/src/lab8/lab8.txt")).setVisible(true);
                } catch (FileNotFoundException ex) {
                    System.out.println("Error: file not found" + ex);
                    System.out.println(System.getProperty("user.dir"));
                }
                //new CompScenarioSim().setVisible(true);
            }
        });
    }

    private LinkedPanel link;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
