/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matthew Laikhram
 */
public class LinkedPanel extends javax.swing.JPanel implements FinishedListener {

    /**
     * Creates new form LinkedPanel
     * @param head
     */
    public LinkedPanel(LinkedPanelNode head) {
        initComponents();
        headPanel = head;
        add(headPanel);
        headPanel.addListener(this);
        headPanel.playMovie();
    }
    
    @Override
    public void fireFinished() {
        if (headPanel.getNext() == null) System.exit(0);
        removeAll();
        headPanel = headPanel.getNext();
        add(headPanel);
        headPanel.addListener(this);
        headPanel.playMovie();
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

    private LinkedPanelNode headPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}